#Startar upp projektet i en Docker‑miljö.
#Definierar en tjänst (app) som bygger från din kod.
#Skapar en volym för att spara databasen utanför containern.
#Sätter miljövariabeln DATABASE_PATH.


version: "3.9"

services:
  app:
    build: .
    container_name: gdpr-user-registry
    volumes:
      - database_data:/data
    environment:
      DATABASE_PATH: /data/test_users.db

volumes:
  database_data:


